#!/bin/bash

rm -rf builddir
meson setup -Dprefix=$HOME/.local builddir

echo "This script should be run only if you are developing or testing the theme."
echo "[b]uild accented icons or [t]est?"
read ANS
if [[ $ANS == "b" ]]; then
	echo "build [a]ll accents?"
	read ANS
	if [[ $ANS == "a" ]]; then
		ninja -C builddir render-accented-icons
	else
		echo "enter accent colour: "
		read ANS
		ninja -C builddir render-icons-$ANS
	fi
elif [[ $ANS == "t" ]]; then
	rm -rf ~/.local/share/icons/Sucharu*
	meson compile -C builddir --verbose
	meson install -C builddir #--dry-run
else
	echo "Choice could not be accepted. Re-run the script and enter correct choice."
fi

echo "Remove meson build directory (\"builddir\")?"
read ans
if [ "$ans" = "Yes" ] || [ "$ans" = "yes" ] || [ "$ans" = "Y" ] || [ "$ans" = "y" ]; then
	rm -rf builddir
fi
